import { useRef,useEffect  } from "react";
import InfoIcon from "../Tooltip/InfoIcon";
export default function ItemCodeInput({
  customClass,
  label,
  inputVal,
  setInputVal,
  important,
  id="",
  maxLength,
  inputRef,
  handleBlur,
  customInputClass,
  placeholder = ""
}) {
  const internalRef = useRef(null);
  useEffect(() => {
    if (inputRef) {
      inputRef.current = internalRef.current;
    }
  }, [inputRef]);
  
  return (
    <div className={`form-group ${
        customClass == null ? "SearchField" : `${customClass}`
      }`}>
      <div className="inputContainer">
        <div className="inputLabel">{label}</div>
        <input
          ref={internalRef}
          onClick={(e) => e.target.select()}
          id={`${id}`}
          type="text"
          className={`form-control item_code_input candela_input ${customInputClass}`}
          value={inputVal}
          onChange={(e) => {
            setInputVal(e.target.value)
          }}
          style={important == "true" ? { backgroundColor: "#FFFFE8" } : {}}
          maxLength={`${maxLength}`}
          onBlur={handleBlur}
          placeholder={placeholder}
        />
        <span className="itemCodeInfoIcon">
          <InfoIcon body={"Item Code can be Numeric or Alpha-Numeric. Max length of the Item Code is defined in 'System Configuration > Item Tab'. If Item coding template is defined, for selected department, then new item code can be generated by pressing 'C' Button."} />
        </span>
      </div>
    </div>
  );
}